version: '3'
services:
  botpress:
    image: botpress/server:12.30.10
    command: ./bp
    environment:
      - BP_HOST=0.0.0.0
      - BP_PORT=3000
      - BP_ADMIN_PASSWORD=your_password_here
      - BP_DATABASE_URL=postgres://postgres:your_db_password@db:5432/botpress_db
    ports:
      - "3000:3000"
    volumes:
      - ./data:/botpress/data
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:11.8-alpine
    environment:
      - POSTGRES_DB=botpress_db
      - POSTGRES_PASSWORD=your_db_password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
